# Generated by Django 4.0.1 on 2022-02-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(verbose_name='total')),
                ('status', models.CharField(choices=[('E', 'Em Análise'), ('A', 'Aprovado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='A', max_length=1, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='produto')),
                ('productid', models.PositiveIntegerField(verbose_name='id produto')),
                ('variation', models.CharField(max_length=100, verbose_name='variação')),
                ('variationid', models.PositiveIntegerField(verbose_name='id variação')),
                ('price', models.FloatField(verbose_name='preço')),
                ('promoprice', models.FloatField(default=0, verbose_name='promocional')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('image', models.CharField(max_length=500, verbose_name='imagem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedidos',
            },
        ),
    ]
