# Generated by Django 4.0.1 on 2022-06-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantidade'),
            preserve_default=False,
        ),
    ]
