# Generated by Django 4.0.1 on 2022-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prodimages/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('promoprice', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('P', 'Padrão'), ('V', 'Variação')], default='D', max_length=1)),
            ],
        ),
    ]
