# Generated by Django 4.0.1 on 2022-01-28 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_prodvariation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='prodvariation',
            options={'verbose_name': 'Varição', 'verbose_name_plural': 'Varições'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prodimages/%Y/%m', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promoprice',
            field=models.FloatField(default=0, verbose_name='promocional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('P', 'Padrão'), ('V', 'Variação')], default='D', max_length=1, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='prodvariation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='prodvariation',
            name='price',
            field=models.FloatField(verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='prodvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='prodvariation',
            name='promoprice',
            field=models.FloatField(default=0, verbose_name='promocional'),
        ),
        migrations.AlterField(
            model_name='prodvariation',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='estoque'),
        ),
    ]
